- Cargo.toml
- src/title/crossfont_renderer.rs
This also enforces the use of system libraries.
> Bump crossfont to 0.5.0

- src/lib.rs
The example title text descents are being clipped. This PR removes that.
> Fix title clipping

- src/title/crossfont_renderer.rs
I noticed this, looks like a typo. I don't think it has any negative effect currently because all font colors are grey at the moment. But probably worth fixing anyway.
> Fix crossfont render color typo

- CHANGELOG.md
- examples/simple.rs
- src/config.rs
- src/lib.rs
- src/theme.rs
Automatically select light/dark theme by querying `org.gnome.desktop.interface.color-scheme` which indicates the light or dark selection in modern gnome "Appearance" settings.
Perhaps there is a better way to query gsettings than running the bin as a command? For me this takes ~2.5ms to run which will happen once on init. Using command is fairly simple and  means no additional dependencies at least.
> Use dbus to hint dark theme preference

- CHANGELOG.md
- Cargo.toml
- src/pointer.rs
- src/title/ab_glyph_renderer.rs
When using `ab_glyph` feature title text try to use system sans font if possible for consistency with `crossfont` feature.
* Instead of `Command` a pure rust fontconfig could work. However, the former does mean no extra dependencies so it's a tradeoff.
* Currently read the system font into heap. We could instead mmap, though I think we'd have to do this for each render call rather than at startup due to borrowing/self ref rules.
I think it makes sense to also lookup from system config the font config for window titles rather than using `sans`.
* Window title font name
* Size
* Variant
For example my gnome tweaks seems to think **"Legacy Window Titles"** should use **"Cantarell Bold 12"**. I'm not sure how to access this data in the most cross-distro way.
Resolves #11
> ab_glyph titles: try to use system sans

- CHANGELOG.md
- Cargo.toml
- examples/simple.rs
- src/config.rs
- src/title.rs
- src/title/ab_glyph_renderer.rs
- src/title/config.rs
- src/title/crossfont_renderer.rs
- src/title/font_preference.rs
This PR uses **gsettings** bin to read `org.gnome.desktop.wm.preferences titlebar-font` _(is there a better way to query this?)_ and use this to configure the font used to render the title (`ab_glyph` and `crossfont`).
If no system font preference is found the default will remain sans:10.
Using gnome (which I'm using) this means the titles look the same as native.
_Example: Top system settings app title, middle `ab_glyph` example title, bottom `crossfont` example title_
~Requires a new _ab_glyph_ & _owned_ttf_parser_ release to support variable font bold logic.~ Update: done.
> Use system titlebar-font config if available

- CHANGELOG.md
- Cargo.toml
- src/buttons.rs
- src/pointer.rs
- src/title/ab_glyph_renderer.rs
- src/title/font_preference.rs
`ab_glyph` titles will read the system title font using memory mapped buffers instead of reading to heap.
This lowers RAM usage of the since previously the system font would be saved in heap. For some system fonts this can be quite large and undesirable for rendering a title.
The disadvantage is currently the font must be parsed before each use instead of once at startup. It may be possible to improve this later with https://github.com/alexheretic/owned-ttf-parser/issues/11. In any case on my system `render()` time is relatively unaffected at 50-100µs so this doesn't seem a deal breaker.
My system title font is Cantarell-VF.otf (167K). Running the `cargo run --example simple --release`
* Before: 570-720K memory
* After: 400-550K memory
If I choose NotoSerifCJK-Bold.ttc (27M). Running the …
> Use memory mapped system fonts for ab_glyph titles instead of keeping in RAM

- Cargo.toml
this adds an unnecessary dependency on the png crate.
> don't use tiny-skia's default features

- src/buttons.rs
- src/config.rs
- src/lib.rs
Closes https://github.com/PolyMeilex/sctk-adwaita/issues/27
In this MR I've generalized the button structure and it is now possible to have custom layouts in window headers similar to what you can have in Gnome apps or classic Xorg WMs.
Obvious use case for this would be to have buttons moved to the left side (like Unity):
But other possible layout combinations should work, too:
or even something crazy like
Also should be extendable if we will (ever) have an app menu button.
I didn't have any experience in rust so far, thus feedback is more than welcomed.
> Support custom header buttons layouts

- CHANGELOG.md
- src/pointer.rs
This should improve the situation with some touchpads. GTK4 is also using the same value.
> Raise double click threshold to 400ms

- src/lib.rs
- src/parts.rs
- src/wl_typed.rs
In order to enable clippy deny panics (#36) we need a way to statically type user data of objects.
> Statically type user data of objects

- CHANGELOG.md
- Cargo.toml
- examples/window.rs
- src/buttons.rs
- src/lib.rs
- src/parts.rs
- src/pointer.rs
- src/wl_typed.rs
This new crate is used to provide common interface for the CSD libraries.
--
Will require a new sctk release to update the example.
> Use `wayland-csd-frame` as a part of public API

- src/lib.rs
When centering the title text in an window of even width, the leftmost pixel of the title text is being cut off. This is because the clip rect is positioned according to x as a floating point, but the pixmap is positioned according to x as cast to an integer. Casting a float to an int floors it.
For example when x is `100.5`, the mask will start at x `100.5`, but the pixmap will be drawn at x `100`, so a bit of the title text will be cut off.
This is noticeable in the following recording, which shows the window being slowly resized. Focus on the bottom-left of the first "/".
[Screencast from 2023-11-10 20-44-40.webm](https://github.com/PolyMeilex/sctk-adwaita/assets/20155479/589b828c-b967-4842-a175-4ce5897ce1c2)
> Fix leftmost title pixel sometimes being cut off

- src/title/ab_glyph_renderer.rs
The `ab_glyph` documentation states:
> A coverage value of 0.0 means the pixel is totally uncoverred by the glyph. A value of 1.0 or greater means fully coverred.
On my machine, this currently results in too high of a alpha value in "self-overlapping" areas, as is especially noticeable in the 'x' and 't' in the following screenshot:
This PR makes it look correct:
> Fix transparency in ab_glyph renderer

- CHANGELOG.md
- src/lib.rs
A better way of drawing a circle using cubic beziers is this: https://stackoverflow.com/a/27863181.
Fixes #49
> Improve roundness of headerbar

- CHANGELOG.md
- src/title/ab_glyph_renderer.rs
ab_glyph apparently likes to draw outside of its area in some cases.
Fixes #50
> Surround the ab_glyph pixmap with a 1px border

- Cargo.toml
This switches the underlying fontconfig-sys crate to yeslogic-fontconfig-sys, due to Servo's lack of maintenance.
> Bump crossfont to 0.8.0

- Cargo.toml
I think types from sctk are used in the public API, so this will probably also require a major version bump for this crate?
> Bump sctk dependency

- CHANGELOG.md
- src/title/ab_glyph_renderer.rs
I saw there were some recent issues with oob on the pixmap when rendering using _ab_glyph_.
The root cause is the use of "layout" positions (font.height(), h_advance etc) to inform the actual rendering pixmap size. The sizes for laying out glyphs are not always the same as the bounds required for actually rendering the glyphs. For example, a glyph at x=0 may have an outline/render that actually includes some pixels to the left of that layout origin.
ab-glyph provides [`OutlinedGlyph::px_bounds`](https://docs.rs/ab_glyph/latest/ab_glyph/struct.OutlinedGlyph.html#method.px_bounds) which accounts for this and will always have enough space to render each pixel returned by [`OutlinedGlyph::draw`](https://docs.rs/ab_glyph/latest/ab_glyph/struct.OutlinedGlyph.html#method.draw) correctly. …
> Improve ab-glyph rendering use outline px_bounds to inform pixmap size

- CHANGELOG.md
- examples/window.rs
- src/lib.rs
- src/parts.rs
Add ability to draw only the window frame, for those who are too lazy to draw decorations themselves but want to implement a custom headerbar (aka. me):
> Add ability to hide the titlebar
